### ISSUE TITLE
Concat error?

### ISSUE THREAD

**Issue by shivam01anand** [ofou/graham-essays#1]
Hey, Thanks a ton for this!
Unfortunately i'm stuck at the final step where i need to concat the md files. The cat function mentioned in the python code wasn't working so i tried a bunch of different libraries. still no luck. Any idea about the line? (python windows)

![image](https://user-images.githubusercontent.com/42206227/103233938-5ebe0200-4964-11eb-95b4-5de3e72c2490.png)

**Comment by philippludwig** [comment]
Yeah, I had to create the `graham.md` file manually as well. Added a heading for each easay while doing this, to maximize readability.

**Comment by ofou** [comment]
Hey guys, sorry for my late reply. I just updated the repo with some minor fixes you both suggested, an improved Makefile and better readability on the EPUB output, plus the latest articles. Hope you enjoy. 

Thanks for your feedback!
