### ISSUE TITLE
2024 update?

### ISSUE THREAD

**Issue by iamrobmat** [ofou/graham-essays#12]
hey, 

there're 3 new writings:

[The Reddits](https://paulgraham.com/reddits.html)
[How to Start Google](https://paulgraham.com/google.html)
[The Best Essay](https://paulgraham.com/best.html)

**Comment by ofou** [comment]
I'll try to update this repo soon, but it should be working fine if you run it locally.

**Comment by ofou** [comment]
@iamrobmat it seems to be working now, check out the [releases](https://github.com/ofou/graham-essays/releases/tag/latest) page for daily updates.
