### ISSUE TITLE
Being able to read the Epub on Kindle.

### ISSUE THREAD

**Issue by arzaanmirza** [ofou/graham-essays#17]
I was hoping if there was a way to send this to my kindle to read. I tried sending the epub to my kindle using the "Send to Kindle" service by Amazon - but it seems like it is unable to be sent as there is some issue with processing it.

I was wondering if anyone knows a way.

**Comment by parkr** [comment]
Consider using Calibre on your computer. You connect your Kindle via USB, add the epubs to Calibre, then select them in Calibre and choose "Send to Device."

**Comment by arzaanmirza** [comment]
Thanks, that worked!

**Comment by kkivan** [comment]
Though it doesn't make book available on all devices
