### ISSUE TITLE
Not supported on Kindle

### ISSUE THREAD

**Issue by Achllle** [ofou/graham-essays#18]
I tried uploading the EPUB using [Amazon's Send To Kindle](https://www.amazon.com/sendtokindle) and it failed twice.

Unfortunately no logs to parse through, just says 'failed to deliver'.

**Comment by arzaanmirza** [comment]
I asked the same question 1 month ago :) -> https://github.com/ofou/graham-essays/issues/17

**Comment by ofou** [comment]
I use Apple Books and it works perfectly for me, try with [this](https://kindle-epub-fix.netlify.app) tool, maybe that helps

**Comment by Achllle** [comment]
Appreciate the suggestions, but I frankly don't want to try a different tool.

**Comment by ofou** [comment]
Is it working now, @Achllle? Can you try with the build from [here](https://github.com/ofou/graham-essays/releases/tag/latest)?

**Comment by Achllle** [comment]
Confirmed this is working with epub file from the above link!
