### ISSUE TITLE
It's not picking up the last essay

### ISSUE THREAD

**Issue by whitenoisedev** [ofou/graham-essays#5]
http://www.paulgraham.com/users.html

Thanks!

**Comment by ofou** [comment]
Thanks for mention it, I'll investigate 🧐

**Comment by ofou** [comment]
Just run the code locally and it adds all the essays. Make sure to run the code locally with all dependencies installed. CI it's just an output example.

**Comment by paramaggarwal** [comment]
Suggestion for anyone interested in contributing: as this is an open-source project, we can run a free GitHub Action that runs weekly and publishes a new version of the book.
