### ISSUE TITLE
EPUB file is corrupt

### ISSUE THREAD

**Issue by georgiai1** [ofou/graham-essays#6]
I tried uploading the EPUB file to my Kobo, but it doesn't open.
Then checked it with [EPUB Validator](https://www.ebookit.com/tools/bp/Bo/eBookIt/epub-validator) and got a lot of errors in conversions.

3 Fatal errors and many minor ones:

- FATAL(RSC-016): ./books/Bo/databases/eBookIt/temp_uploads/1673860091.epub/EPUB/text/ch088.xhtml(80,17): Fatal Error while parsing file: The element type "quotation" must be terminated by the matching end-tag "".
- FATAL(RSC-016): ./books/Bo/databases/eBookIt/temp_uploads/1673860091.epub/EPUB/text/ch148.xhtml(35,143): Fatal Error while parsing file: Attribute name "Name" associated with an element type "Your" must be followed by the ' = ' character.
- FATAL(RSC-016): ./books/Bo/databases/eBookIt/temp_uploads/1673860091.epub/EPUB/text/ch189.xhtml(36,565): Fatal Error while parsing file: The element type "outgroup" must be terminated by the matching end-tag "".

PS. Table of content in the EPUB and MOBI will be helpful for easy jumping to specific essays

**Comment by ofou** [comment]
Something must be broken on the CI that is creating the EPUB. 

I'll circle back soon.

**Comment by georgiai1** [comment]
@ofou Thanks

**Comment by georgiai1** [comment]
Building it from the source worked. Prebuild file is still corrupt.

**Comment by ofou** [comment]
Thanks!
